SELECT [ODR.ORDER_DATE_EOM]
    ,[CLNT.CLIENT_ID]
    ,[CLNT.CLIENT_NAME]
    ,[OITM.PRODUCT_ID]
    ,SUM([OITM.ITEM_QTY]) AS TOTAL_QTY    
FROM [ORDER_ITEM] OITM
LEFT JOIN (
    SELECT ORDER_ID
        ,ORDER_DATE
        ,EOMONTH(ORDER_DATE) AS ORDER_DATE_EOM
        ,CLIENT_CUSTOMER_ID
    FROM [ORDER]
) ODR 
    ON [OITM.ORDER_ID] = [ODR.ORDER_ID]
LEFT JOIN [CLIENT_CUSTOMER] CLCS
    ON [ODR.CLIENT_CUSTOMER_ID] = [CLCS.CLIENT_CUSTOMER_ID]
LEFT JOIN [CLIENT] CLNT
    ON [CLCS.CLIENT_ID] = [CLNT.CLIENT_ID]
LEFT JOIN [PRODUCT] PDCT
    ON [OITM.PRODUCT_ID] = [PDCT.PRODUCT_ID]
LEFT JOIN [PRODUCT_CATEGORY] PRCG
    ON [PDCT.PRODUCT_CATEGORY_ID] = [PRCG.PRODUCT_CATEGORY_ID]
LEFT JOIN [PRODUCT_VENDOR] PRVD
    ON [PDCT.PRODUCT_VENDOR_ID] = [PRVD.PRODUCT_VENDOR_ID]
WHERE [PRVD.PRODUCT_VENDOR_NAME] = 'TRANSUNION'
    AND [PRCG.PRODUCT_CATEGORY_DESCR] = 'FULL CREDIT REPORT'
GROUP BY [ODR.ORDER_DATE_EOM]
    ,[CLNT.CLIENT_ID]
    ,[CLNT.CLIENT_NAME]
    ,[OITM.PRODUCT_ID]