-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-04-15 04:35:10.869

-- tables
-- Table: CLIENT
CREATE TABLE CLIENT (
    CLIENT_ID int  NOT NULL IDENTITY(1, 1),
    CLIENT_NAME NVARCHAR(500)  NOT NULL,
    CONSTRAINT CLIENT_ID PRIMARY KEY  (CLIENT_ID)
);

-- Table: CLIENT_CUSTOMER
CREATE TABLE CLIENT_CUSTOMER (
    CLIENT_CUSTOMER_ID int  NOT NULL IDENTITY(1, 1),
    CLIENT_CUSTOMER_NAME NVARCHAR(500)  NOT NULL,
    CLIENT_CUSTOMER_EXTERNAL_ID NVARCHAR(500)  NOT NULL,
    CLIENT_ID int  NOT NULL,
    CONSTRAINT CLIENT_CUSTOMER_pk PRIMARY KEY  (CLIENT_CUSTOMER_ID)
);

-- Table: ORDER
CREATE TABLE "ORDER" (
    ORDER_ID int  NOT NULL IDENTITY(1, 1),
    ORDER_DATE DATETIME  NOT NULL,
    CLIENT_CUSTOMER_ID int  NOT NULL,
    CONSTRAINT ORDER_pk PRIMARY KEY  (ORDER_ID)
);

-- Table: ORDER_ITEM
CREATE TABLE ORDER_ITEM (
    ORDER_ITEM_ID int  NOT NULL IDENTITY(1, 1),
    ITEM_QTY int  NOT NULL,
    ORDER_ID int  NOT NULL,
    PRODUCT_ID int  NOT NULL,
    CONSTRAINT ORDER_ITEM_pk PRIMARY KEY  (ORDER_ITEM_ID)
);

-- Table: PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_ID int  NOT NULL IDENTITY(1, 1),
    PRODUCT_DESCR NVARCHAR(500)  NOT NULL,
    PRODUCT_VENDOR_ID int  NOT NULL,
    PRODUCT_CATEGORY_ID int  NOT NULL,
    CONSTRAINT PRODUCT_pk PRIMARY KEY  (PRODUCT_ID)
);

-- Table: PRODUCT_CATEGORY
CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_CATEGORY_ID int  NOT NULL,
    PRODUCT_CATEGORY_DESCR NVARCHAR(500)  NOT NULL,
    CONSTRAINT PRODUCT_CATEGORY_pk PRIMARY KEY  (PRODUCT_CATEGORY_ID)
);

-- Table: PRODUCT_VENDOR
CREATE TABLE PRODUCT_VENDOR (
    PRODUCT_VENDOR_ID int  NOT NULL,
    PRODUCT_VENDOR_NAME int  NOT NULL,
    CONSTRAINT PRODUCT_VENDOR_pk PRIMARY KEY  (PRODUCT_VENDOR_ID)
);

-- foreign keys
-- Reference: CLIENT_CUSTOMER_CLIENT (table: CLIENT_CUSTOMER)
ALTER TABLE CLIENT_CUSTOMER ADD CONSTRAINT CLIENT_CUSTOMER_CLIENT
    FOREIGN KEY (CLIENT_ID)
    REFERENCES CLIENT (CLIENT_ID);

-- Reference: ORDER_CLIENT_CUSTOMER (table: ORDER)
ALTER TABLE "ORDER" ADD CONSTRAINT ORDER_CLIENT_CUSTOMER
    FOREIGN KEY (CLIENT_CUSTOMER_ID)
    REFERENCES CLIENT_CUSTOMER (CLIENT_CUSTOMER_ID);

-- Reference: ORDER_ITEM_ORDER (table: ORDER_ITEM)
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES "ORDER" (ORDER_ID);

-- Reference: ORDER_ITEM_PRODUCT (table: ORDER_ITEM)
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCT (PRODUCT_ID);

-- Reference: PRODUCT_PRODUCT_CATEGORY (table: PRODUCT)
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PRODUCT_CATEGORY
    FOREIGN KEY (PRODUCT_CATEGORY_ID)
    REFERENCES PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID);

-- Reference: PRODUCT_PRODUCT_VENDOR (table: PRODUCT)
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PRODUCT_VENDOR
    FOREIGN KEY (PRODUCT_VENDOR_ID)
    REFERENCES PRODUCT_VENDOR (PRODUCT_VENDOR_ID);

-- End of file.

